baseURL = "/"
theme = "hugo-whisper-theme"
languageCode = "en-us"
title = "MakeSign"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'MakeSign is a University Project offering a simple Digital Signage solution.'
  homepage_image = '/images/Makesign(1).png'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "MakeSign is a University Project offering a simple Digital Signage solution."
    meta_og_title = "MakeSign"
    meta_og_type = "website"
    meta_og_description = "MakeSign is a University Project offering a simple Digital Signage solution"

  [params.logo]
      mobile = "/images/MakeSign_Logo.svg"
      standard  = "/images/MakeSign_Logo.svg"

  [params.footer]
    copyright_text = 'Free Hugo theme by <a class="zerostatic" href="https://www.zerostatic.io">Zerostatic Themes</a>'
